/* ============================================================
   ★★★ 데이터 관리 구역 ★★★
   수정이 필요할 때는 이 파일(SERVICES, WORKS)만 건드리면 됩니다.
   이미지 파일은 assets/images/ 폴더에 업로드하세요.
   ============================================================ */

const SERVICES = [
  {
    no: '01',
    title: '디지털 전단지',
    desc: '종이 전단지를 모바일 한 장으로. QR 한 번에 열리는 페이지로 메뉴·가격·예약을 매번 새로 인쇄할 필요 없이 즉시 반영합니다.',
    tags: ['QR 발급', '구글시트 연동', '다국어'],
  },
  {
    no: '02',
    title: '홈페이지 제작 + 구독',
    desc: '만들고 끝나지 않는 홈페이지. 업종에 맞춰 처음부터 새로 디자인하고, 매달 구독으로 콘텐츠와 이미지를 함께 다듬습니다.',
    tags: ['맞춤 디자인', '월 구독', '도메인·호스팅 관리'],
  },
  {
    no: '03',
    title: '학원 솔루션 랜딩',
    desc: '학원 운영의 모든 것을 한 페이지로. 출결·학생 관리·채점 시스템 소개와 학부모 상담 신청 폼까지 한 곳에 정리합니다.',
    tags: ['커리큘럼', '강사 소개', '상담 폼'],
  },
  {
    no: '04',
    title: '홍보 동영상 제작',
    desc: 'AI 생성과 직접 촬영, 두 가지 방식으로. 빠르고 가벼운 홍보 영상부터 정성껏 촬영한 브랜드 영상까지 업종에 맞춰 제작합니다.',
    tags: ['AI 생성', '현장 촬영', 'SNS 최적화'],
  },
  {
    no: '05',
    title: '부동산 · 병원 특화 패키지',
    desc: '전문 영역에 맞춘 별도 패키지. 부동산은 매물 카드와 지역 정보를, 병원은 진료과목과 예약 폼을 업종 가이드라인에 맞춰 구성합니다.',
    tags: ['업종 맞춤', '예약 폼', '규제 준수'],
  },
];

const WORKS = [
  // ── LocalBoost 자체 제작 샘플 (가상 업체, 포트폴리오용) ──
  {
    name: '돌담 스테이',
    client: 'Jeju Boutique Pension',
    tag: '숙박',
    status: 'Sample',
    desc: '제주 조천 바닷가 언덕의 독채 3동. 노천탕·인피니티풀·셰프 조식을 갖춘 프리미엄 부티크 스테이 샘플.',
    url: 'samples/stay.html',
    location: '제주 조천',
    img: 'sample-stay.svg',
  },
  {
    name: '한담 스테이',
    client: 'Handam Oceanview Stay',
    tag: '숙박',
    status: 'Sample',
    desc: '애월 한담해안산책로 앞 오션뷰 부티크 스테이 샘플. 창 바로 앞의 바다, 프라이빗 풀 스위트 포함.',
    url: 'samples/handam.html',
    location: '제주 애월 한담',
    img: 'sample-handam.svg',
  },
  {
    name: '오름 스테이',
    client: 'Hilltop Villa Stay',
    tag: '숙박',
    status: 'Sample',
    desc: '제주 동부 오름 자락 억새밭 힐탑 스테이 샘플. 독채 3동 · 일출·선셋·파노라마 뷰 + 일출 트레킹 체험 프로그램.',
    url: 'samples/oreum.html',
    location: '제주 동부',
    img: 'sample-oreum.svg',
  },
  {
    name: '단담 스튜디오',
    client: 'Interior · Architecture',
    tag: '인테리어',
    status: 'Sample',
    desc: '주거·상업·세컨드 하우스 전문 인테리어 스튜디오 포트폴리오 샘플. 건축가 포트폴리오 톤의 에디토리얼 레이아웃.',
    url: 'samples/interior.html',
    location: '서울 성수',
    img: 'sample-interior.svg',
  },
  {
    name: '온화 의원',
    client: 'Family Medicine Clinic',
    tag: '병원',
    status: 'Sample',
    desc: '가정의학과·내과 동네 의원 샘플. 웜톤 부티크 톤 · 진료과목·의료진·진료시간·예약까지 한 페이지에.',
    url: 'samples/clinic.html',
    location: '제주 연동',
    img: 'sample-clinic.svg',
  },
  {
    name: '세움 학원',
    client: 'K-12 Private Academy',
    tag: '학원',
    status: 'Sample',
    desc: '초·중등 입시 전문 학원 샘플. 개별 자습 부스 + 소수 정예 클래스 구조. 커리큘럼·선생님·시간표·상담 신청까지.',
    url: 'samples/academy.html',
    location: '제주 신제주',
    img: 'sample-academy.svg',
  },
  {
    name: '무드 네일',
    client: 'Private Nail Studio',
    tag: '네일샵',
    status: 'Sample',
    desc: '1인 네일 스튜디오 샘플. 뉴트럴 팔레트 · 시그니처 메뉴 8종 · 갤러리 · 원장 소개 · 예약 안내.',
    url: 'samples/nail.html',
    location: '제주 연동',
    img: 'sample-nail.svg',
  },

  // ── 실제 클라이언트 제작 사례 ──
  {
    name: '고기편애',
    client: 'Jeju Premium Meat Restaurant',
    tag: '고깃집',
    status: 'Live',
    desc: '제주 한우·흑돼지 전문점. 메뉴 가이드, 한·영·중 다국어 지원, 브랜드 스토리 포함 프리미엄 다이닝 사이트.',
    url: 'https://ian0417kim-afk.github.io/gogipyeonae/',
    location: '제주',
    img: 'sample-gogi.svg',
  },
  {
    name: '정든부동산',
    client: 'Jeju Real Estate',
    tag: '부동산',
    status: 'Live',
    desc: '제주 공인중개사 디지털 전단지. 실사진 매물 슬라이더, 한·영·중 3개 언어, SMS 문의 버튼.',
    url: 'https://ian0417kim-afk.github.io/jung-deun/',
    location: '제주시 일주서로',
    img: 'img-jungdeun.png',
  },
  {
    name: '돈나무',
    client: 'Jeju Restaurant',
    tag: '식당',
    status: 'Live',
    desc: '제주 흑돼지 전문 식당 디지털 전단지. 메뉴판, 한·영·중 다국어, 예약 및 문의 버튼.',
    url: 'https://ian0417kim-afk.github.io/donnamu1/',
    location: '제주',
    img: 'img-donnamu.png',
  },
  {
    name: '화북영어나무',
    client: 'English Academy',
    tag: '영어학원',
    status: 'Live',
    desc: '제주 화북 영어 전문 학원 디지털 전단지. 커리큘럼, 수강 안내, 상담 예약.',
    url: 'https://ian0417kim-afk.github.io/JEJUSAMHWADISTRICT2/',
    location: '제주시 화북',
    img: 'img-englishnamu.png',
  },
  {
    name: '제주숙소 플랫폼',
    client: 'Jeju Stay Platform',
    tag: '숙박',
    status: '제작중',
    desc: '제주 숙박 업체 통합 플랫폼 — 객실 소개, 예약, 위치 안내, 다국어 지원.',
    url: 'https://ian0417kim-afk.github.io/localboost1/',
    location: '준비 중',
    img: 'img-jejustay.jpg',
  },
  {
    name: '올라운더',
    client: 'Fitness Gym',
    tag: '헬스짐',
    status: '제작중',
    desc: '제주 헬스짐 디지털 전단지. 프로그램 소개, 요금 안내, 무료 체험 신청.',
    url: 'https://ian0417kim-afk.github.io/arrround1/',
    location: '서귀포 동홍동',
    img: 'a1.png',
  },
  {
    name: '릿츄업 학원',
    client: 'Education · Academy',
    tag: '학원',
    status: 'Sample',
    desc: '학원 디지털 전단지 샘플. 프로그램 소개, 강사 프로필, 수강료 안내, 상담 예약.',
    url: 'https://ian0417kim-afk.github.io/LITYOUUP/',
    location: '제작 샘플',
    img: 'h1.png',
  },
  {
    name: '제주밝음내과',
    client: 'Medical Clinic',
    tag: '병원',
    status: '제작중',
    desc: '내과 · 가정의학과 디지털 전단지 샘플. 진료과목, 시간표, 온라인 예약 포함.',
    url: 'https://ian0417kim-afk.github.io/localboost/hospital.html',
    location: '제작 샘플',
  },
  {
    name: '보험설계사 K',
    client: 'Insurance Planner',
    tag: '보험',
    status: '제작중',
    desc: '보험설계사 개인 홍보물. 상품 소개, 상담 예약, 연락처 안내.',
    url: 'https://ian0417kim-afk.github.io/choikim1/',
    location: '제주',
    img: 'b1.png',
  },
  {
    name: '푸른숲리조트',
    client: 'Jeju Forest Resort',
    tag: '숙박',
    status: '제작중',
    desc: '제주 한림 프라이빗 숲속 리조트. 독립 객실 11동, 반려견 동반 가능, 야외수영장, 4개 언어 지원.',
    url: 'https://ian0417kim-afk.github.io/jejugreenforest1/?v=2',
    location: '제주시 한림읍',
    img: 'FF1.png',
  },
  {
    name: '글라스바바',
    client: 'Optical Shop',
    tag: '안경점',
    status: '제작중',
    desc: '제주 안경 전문점 디지털 전단지. 안경·선글라스·렌즈 안내, 위치 정보, 다국어 지원.',
    url: 'https://ian0417kim-afk.github.io/grassbabajeju/',
    location: '제주',
    img: 'AA1.png',
  },
  // ▼ 새 업체 추가 시 아래 주석을 복사해서 사용하세요
  // {
  //   name: '업체명',
  //   client: 'English Name',
  //   tag: '업종',
  //   status: 'Live',
  //   desc: '업체 설명',
  //   url: 'https://링크주소',
  //   location: '지역명',
  //   img: '파일명.jpg',
  // },
];
